app/admin/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField
from wtforms.validators import DataRequired, EqualTo, Email, ValidationError
from app.models import User
from app.validators import validate_username, validate_email


class CreateUserForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired()])
    full_name = StringField("Full Name", validators=[DataRequired()])
    email = StringField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[DataRequired()])
    password2 = PasswordField("Password", validators=[
                              DataRequired(), EqualTo("password")])

    # automatically used by wtforms
    # username already taken?
    def validate_username(self, username) -> None:
        validate_username(username.data)

    # email already taken?
    def validate_email(self, email) -> None:
        validate_email(email.data)

app/admin/__init__.py
from flask import Blueprint

bp = Blueprint("admin", __name__, template_folder="templates")

from app.admin import routes

app/admin/routes.py
from datetime import datetime

from app import db
from app.admin import bp
from app.admin.forms import CreateUserForm
from app.auth.access import admin_required
from app.models import User
from flask import (current_app, flash, redirect, render_template, request,
                   url_for)
from flask.json import jsonify
from flask_login import current_user
from flask_login.utils import login_required


# includes user creation form
@bp.route("/users")
@login_required
def users():
    admin_required()
    page = request.args.get("page", 1, type=int)
    users = User.query.order_by(User.is_admin.desc(), User.is_author.desc(), User.last_seen.desc()).paginate(
        page, current_app.config["USERS_PER_PAGE"], False)
    # None or pagination links
    prev_url = url_for(
        "admin.users", page=users.prev_num) if users.has_prev else None
    next_url = url_for(
        "admin.users", page=users.next_num) if users.has_next else None
    return render_template("user_overview.html", users=users.items, prev_url=prev_url, next_url=next_url, amount_pages=users.pages, title="User Overview")


# includes user creation form
@bp.route("/create_user", methods=["GET", "POST"])
@login_required
def create_user():
    admin_required()
    form = CreateUserForm()
    if form.validate_on_submit():
        user = User(username=form.username.data,
                    email=form.email.data,
                    full_name=form.full_name.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash(f"{form.username.data} has been created.", "info")
        return redirect(url_for("admin.users"))
    return render_template("create_user.html", form=form, title="Create User")


# ajax
@bp.route("/set_admin", methods=["POST"])
@login_required
def set_admin():
    admin_required()
    # todo: type might not be correct <- bad trust in client
    username: str = request.json["username"]
    status: bool = request.json["status"]
    user = User.query.filter_by(username=username).first()
    if user and user != current_user:
        user.change_admin_status(status)
        db.session.commit()
        return jsonify({"success": True, "status": status})
    return jsonify({"success": False})


# ajax
@bp.route("/set_author", methods=["POST"])
@login_required
def set_author():
    admin_required()
    # todo: type might not be correct <- bad trust in client
    username: str = request.json["username"]
    status: bool = request.json["status"]
    user = User.query.filter_by(username=username).first()
    if user:
        user.change_author_status(status)
        db.session.commit()
        return jsonify({"success": True, "status": status, "reload_page": user == current_user})
    return jsonify({"success": False})


# delete user
@bp.route("/delete_user/<username>")
@login_required
def delete_user(username: str):
    admin_required()
    user = User.query.filter_by(username=username).first()
    if not user or user == current_user:
        return redirect(url_for("admin.users"))
    return render_template("delete_user.html", user=user, title="Delete User")


# actually deleting an account
# ajax
@bp.route("/confirm_delete_user", methods=["POST"])
@login_required
def confirm_delete_user():
    admin_required()
    username = request.json["id"]
    # searching for user
    user = User.query.filter_by(username=username).first()
    if user and user != current_user:
        # deleting the user
        db.session.delete(user)
        db.session.commit()
        flash('{} has been deleted!'.format(user.username), "info")
        return jsonify({'success': True})
    return jsonify({'success': False})

app/admin/templates/create_user.html
{% extends "base.html" %}

{% block content %}
<h1>Create New User</h1>
<form action="" method="post">
    {{ form.hidden_tag() }}

    {% with %}
    {% set form_element = form.username %}
    {% include "_text_input.html" %}
    {% endwith %}

    {% with %}
    {% set form_element = form.full_name %}
    {% include "_text_input.html" %}
    {% endwith %}

    {% with %}
    {% set form_element = form.email %}
    {% include "_text_input.html" %}
    {% endwith %}

    {% with %}
    {% set form_element = form.password %}
    {% include "_password_input.html" %}
    {% endwith %}

    {% with %}
    {% set form_element = form.password2 %}
    {% include "_password_input.html" %}
    {% endwith %}

    <button type="submit" class="btn btn-primary">Create User</button>
</form>
{% endblock %}

app/admin/templates/delete_user.html
{% extends "base.html" %}

{% block content %}
<h3>User Deletion</h3>
<p>Are you sure you want to permanently remove <b>{{ user.full_name }}</b> a.k.a. <b>{{ user.username }}</b>?</p>

{% with %}
{% set id=user.username %}
{% set url=url_for('admin.users') %}
{% set text="Delete User" %}
{% set timeout=3000 %}
{% include "_confirm_delete_button.html" %}
{% endwith %}
{% endblock %}

{% block scripts %}
<ajax_url id="confirm-delete" url="{{ url_for('admin.confirm_delete_user') }}" csrf_token="{{ csrf_token() }}" />

<script src="{{ url_for('static', filename='js/delete.js') }}"></script>
{% endblock %}

app/admin/templates/user_overview.html
{% extends "base.html" %}

{% block content %}
<h1>User Overview</h1>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Full Name</th>
            <th scope="col">Last Seen</th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        {% for user in users %}
        <tr>
            <td>
                {{ user.username }}
                <div class="is-admin {% if not user.is_admin %}default-hidden{% else %}default-inline{% endif %}"
                    data-id="{{ user.username }}">👑</div>
                <div class="is-author {% if not user.is_author %}default-hidden{% else %}default-inline{% endif %}"
                    data-id="{{ user.username }}">📕</div>
            </td>
            <td>
                {{ user.full_name }}
            </td>
            <td>
                <div class="moment-from-now" data-time="{{ user.last_seen }}"></div>
            </td>

            <td>
                <button {% if user==current_user %}disabled{% endif %} type="button" class="btn btn-primary button-link"
                    data-url="{{ url_for('auth.settings', username=user.username) }}">
                    Change Settings
                </button>
            </td>
            <td>
                {% with %}
                {% set class="btn-warning toggle-author" %}
                {% set status=user.is_author %}
                {% set true_text="Revoke Author" %}
                {% set false_text="Make Author" %}
                {% set data={"username":user.username} %}
                {% include "_toggle_button.html" %}
                {% endwith %}
            </td>
            <td>
                {% with %}
                {% set class="btn-warning toggle-admin" %}
                {% set status=user.is_admin %}
                {% set true_text="Revoke Admin" %}
                {% set false_text="Make Admin" %}
                {% set data={"username":user.username} %}
                {# can't revoke one self #}
                {% set disabled=user == current_user %}
                {% include "_toggle_button.html" %}
                {% endwith %}
            </td>
            <td>
                <button {% if user==current_user %}disabled{% endif %} type="button" class="btn btn-danger button-link"
                    data-url="{{ url_for('admin.delete_user', username=user.username) }}">
                    Delete User
                </button>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% with %}
{% set address="admin.users" %}
{% include "_pagination_links.html" %}
{% endwith %}

<button type="button" class="btn btn-primary button-link" data-url="{{ url_for('admin.create_user') }}">
    Create User
</button>

{% endblock %}

{% block scripts %}
<ajax_url id="set-admin" url="{{ url_for('admin.set_admin') }}" csrf_token="{{ csrf_token() }}" />
<ajax_url id="set-author" url="{{ url_for('admin.set_author') }}" csrf_token="{{ csrf_token() }}" />

<script src="{{ url_for('static', filename='js/users.js') }}"></script>
{% endblock %}

app/admin/templates/users.html
{% extends "base.html" %}

{% block content %}
<h1>User Overview</h1>
<table class="table">
    <thead>
        <tr>
            <th scope="col">name</th>
            <th scope="col">full_name</th>
            <th scope="col">last seen</th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        {% for user in users %}
        <tr>
            <td>
                {{ user.username }}
                <div class="is-admin {% if not user.is_admin%}default-hidden{% else %}default-inline{% endif %}"
                    data-username="{{ user.username }}">👑</div>
                <div class="is-author {% if not user.is_author%}default-hidden{% else %}default-inline{% endif %}"
                    data-username="{{ user.username }}">📕</div>
            </td>
            <td>
                {{ user.full_name }}
            </td>
            <td>
                <div class="moment-from-now" data-time="{{ user.last_seen }}"></div>
            </td>

            <td>
                <button {% if user==current_user %}disabled{% endif %} type="button" class="btn btn-primary button-link"
                    data-url="{{ url_for('auth.settings', username=user.username) }}">
                    Change Settings
                </button>
            </td>
            <td>
                {% with %}
                {% set class="btn-warning toggle-author" %}
                {% set status=user.is_author %}
                {% set true_text="Revoke Author" %}
                {% set false_text="Make Author" %}
                {% set data={"username":user.username} %}
                {% include "_toggle_button.html" %}
                {% endwith %}
            </td>
            <td>
                {% with %}
                {% set class="btn-warning toggle-admin" %}
                {% set status=user.is_admin %}
                {% set true_text="Revoke Admin" %}
                {% set false_text="Make Admin" %}
                {% set data={"username":user.username} %}
                {# can't revoke one self #}
                {% set disabled=user == current_user %}
                {% include "_toggle_button.html" %}
                {% endwith %}
            </td>
            <td>
                <button {% if user==current_user %}disabled{% endif %} type="button" class="btn btn-danger button-link"
                    data-url="{{ url_for('admin.delete_user', username=user.username) }}">
                    Delete User
                </button>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<nav aria-label="Users Pagination">
    <ul class="pagination">
        <li class="page-item {% if not prev_url %}disabled{% endif %}"><a class="page-link"
                href="{{ url_for('admin.users', page=1) }}">1</a></li>
        <li class="page-item {% if not prev_url %}disabled{% endif %}"><a class="page-link"
                href="{{ prev_url }}">Previous</a></li>
        <li class="page-item {% if not next_url %}disabled{% endif %}"><a class="page-link"
                href="{{ next_url }}">Next</a></li>
        <li class="page-item {% if not next_url %}disabled{% endif %}"><a class="page-link"
                href="{{ url_for('admin.users', page=amount_pages) }}">{{ amount_pages }}</a></li>
    </ul>
</nav>
{% endblock %}

{% block scripts %}
<ajax_url id="set-admin" url="{{ url_for('admin.set_admin') }}" />
<ajax_url id="set-author" url="{{ url_for('admin.set_author') }}" />

<script type="module" src="{{ url_for('static', filename='js/users.js') }}"></script>
{% endblock %}